### PR TITLE
Add Nextclade v3 alpha; remove Nextclade v1

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
## Description of proposed changes

- [x] Add Nextclade v3 alpha release as `nextclade3`. We can start upgrading pipelines to v3. The downloaded version is currently hardcoded.
- [x] Freeze Nextclade v2 to the exact version 2.14.0. This is the latest version with major 2 and there will be no more updates. The binaries are called `nextclade2` and `nextalign2`. They are symlinked to `nextclade` and `nextalign` respectively, so that this version is still the default.
- [x] Remove Nextclade v1 (binaries `nextclade1` and `nextalign1`) - it is obsolete and it is not adequate scientifically anymore, so if something happens to break missing v1 it should be fixed by upgrading.

#### TODO after final v3 release:
- replace download link with hardcoded alpha version to the link to latest version
- symlink `nextclade` to `nextclade3`, making it default
- either symlink `nextalign` to `nextclade3`, or, preferably, consider removing `nextalign` symlink.

#### Useful links:

- GitHub release: https://github.com/nextstrain/nextclade/releases/tag/3.0.0-alpha.0
- Slack thread: https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1701151846934669

## Checklist

- [x] Checks pass
- [x] Binary versions are as expected on PR branch's preview image:

    ```
    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade3 --version
    nextclade 3.0.0-alpha.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade --version
    nextclade 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextalign --version
    nextalign 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade2 --version
    nextclade 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextalign2 --version
    nextalign 2.14.0
    ```

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
I had to move v2 downloads from stage 2 (before CACHE_DATE) to stage 3 (after CACHE_DATE) because `/builder-scripts/target-triple` is no available in stage 2. This was an easy solution, but it might not be the optimal one. Please comment which is preferrable.

**Comment by ivan-aksamentov** [comment]
@corneliusroemer I don't see why we'd include multiple versions in the conda package. Conda packages are already versioned, so for sticking to v2 you'd just `conda install nextclade=2.14.0` (or whatever the conda syntax is). I did not think to include multiple binaries there.

What I am talking about is that I cannot release `3.0.0-alpha.0` to conda without breaking `conda install nextclade` (latest version) right now.

If you mean that we can release conda package versioned `3.0.0-alpha.0` and it would have `nextclade` default binary `2.14.0`, as well as `nextclade3` binary `3.0.0-alpha.0`, then I find it misleading. That's too "smart" and unexpected. I would not like anyone to pull this trick on me with the packages I use.

Anyways, this PR is about `docker-base` and the conda problems are to be solved in the places where it is used, if any. Or these places can just wait the final release.

**Review by victorlin — CHANGES_REQUESTED** [review]
Changes seem reasonable. I think eeaedcfdc9096d6eac882a57c2d466917eedeb32 can be reworked to leverage caching for v2 - I'll push a change.

**Comment by victorlin** [comment]
@corneliusroemer thanks for following up. I pushed the requested changes. Will run a quick test now on the preview image then merge when it looks good.

**Review by victorlin — APPROVED** [review]
- [x] Binary versions are as expected on PR branch's preview image:

    ```
    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade3 --version
    nextclade 3.0.0-alpha.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade --version
    nextclade 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextalign --version
    nextalign 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextclade2 --version
    nextclade 2.14.0

    $ docker run --rm -it docker.io/nextstrain/base:branch-nextclade-v3 nextalign2 --version
    nextalign 2.14.0
    ```

**Comment by victorlin** [comment]
@corneliusroemer `nextclade3` is available as of `docker.io/nextstrain/base:build-20231130T175113Z`.

**Pull request merged**
